# Generated by Django 3.1.5 on 2021-06-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worxpro', '0002_user_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(default='NEWLY LOGGED', max_length=50),
        ),
    ]
