# Generated by Django 3.1.5 on 2021-06-30 17:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('worxpro', '0003_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='time_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
